### ISSUE TITLE
Create an instance for uniprot

### ISSUE THREAD

**Issue by ColinMaudry** [ColinMaudry/sparql-router#38]
http://sparql.uniprot.org/

@JervenBolleman ;)

**Comment by JervenBolleman** [comment]
hmm, what would you like us to do specifically?

**Comment by ColinMaudry** [comment]
Nothing! I'll set up a instance of SPARQL router that will enable the creation and sharing of queries that hit Uniprot's endpoint. That can be usesul if you want to share query results.
